---
title: "MATH 341 - Homework 02"
author: "Marjorie Blanco"
date: "January 3, 2018"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

# Problem 1


```{r}
n <- 15
p <- 0.2
q <- 1 - p

mean <- n * p

sigma <- sqrt(mean * q)

df <- data.frame(x=0:n, prob=dbinom(0:n, n, prob=p))
df$cprob <- pbinom(0:n, n, prob=p)
df

ggplot(data=df, aes(x=x,y=prob)) + 
  geom_line() +
  geom_ribbon(data=subset(df,x==15),aes(ymax=prob),ymin=0,
                  fill="red", colour = NA, alpha = 0.5)

# All 15 drives will have a blood alcohol level exceeding the legal limit.
#a. p(y = 15)
#binompdf(15,0.02,15)

dbinom(15, size=15, prob=0.2) 

# Exactly 6 of the 15 drives will exceed the legal limit
#b. p(y = 6)
#binompdf(15,0.02,6)

dbinom(6, size=15, prob=0.2) 


# Of the 15 drivers, 6 or more will exceed the legal limit
#c. p(y >= 6) = 1 - p(y <= 5)
#1 - binomcdf(15,0.02,5)

1 - pbinom(5, size=15, prob=0.2)
ggplot(data=df, aes(x=x,y=prob)) + 
  geom_line() +
  geom_ribbon(data=subset(df,x>=6 & x<=15),aes(ymax=prob),ymin=0,
                  fill="red", colour = NA, alpha = 0.5)

# All 15 drivers will have a blood alcohol level within the legal limit
#d. p(y = 0)
#binompdf(15,0.02,0)
pbinom(0, size=15, prob=0.2) 
```

# Problem 2

```{r}
n <- 6

df <- data.frame(x=0:n, prob=ppois(0:n, n))
df

ggplot(data=df, aes(x=x,y=prob)) + 
  geom_line()

# No customers arrive
# p(y = 0)
#poissonpdf(6,0)
dpois(0,6)

# More than six customers arrive
#b. p(y > 6) = 1 - p(y <= 5)
# 1 - poissoncdf(6,6)

1-ppois(6,6)

# At most three customer arrive
#c. p(y <= 3)
#poissoncdf(6,3)

ppois(3,6)
```

# Problem 3
Find the probability of 8 or more women being laid off by chance alone.

```{r}
n <- 30
w <- 12
m <- 18
l <- 10

dhyper(8, w, m, l)

df <- data.frame(x=0:8, prob=dhyper(0:8, w, m, l))
df$prob1 <- phyper(0:8, w, m, l)
df

ggplot(data=df, aes(x=x,y=prob)) + 
  geom_line()
```

# Problem 4

```{r}
rate <- 1/20

# You will wait for more than 10 mins
#p (y >= 10)

1 - pexp(10, rate)

# You will wait for 6 mins or less
#p ( y <= 6)

pexp(6, rate)


# You will wait between 8 and 15 mins
#p ( 8 <= y <= 15) 

a <- 1 - pexp(15, rate) 
b <- 1 - pexp(8, rate)
b - a
```